import Link from "next/link";
import { MarketingShell } from "@/components/layout/marketing-shell";

export default function AboutPage() {
  return (
    <MarketingShell>
      <article className="mx-auto max-w-3xl px-4 py-20">
        <p className="font-display text-lg italic tracking-[0.35em] text-accent-primary">
          ABOUT
        </p>
        <h1 className="mt-4 font-heading text-4xl text-text-primary">
          Privacy, terms & safety
        </h1>
        <div className="mt-8 space-y-4 text-sm leading-relaxed text-text-secondary">
          <p>
            Qarar provides decision-analysis support — not medical, legal, financial, or mental-health
            advice. Autopsies are generated by AI and should be treated as structured reflection tools,
            not professional guidance.
          </p>
          <p>
            Your decision narratives are stored securely and scoped to your account. You can export or
            delete your data anytime from Settings. We do not sell personal decision content.
          </p>
          <p>
            Crisis language is blocked before analysis. If you are in immediate danger, contact local
            emergency services or a trusted person — Qarar is not an emergency service.
          </p>
          <p>
            Replace this page with counsel-reviewed privacy policy and terms of service before public
            launch.
          </p>
        </div>
        <p className="mt-8 text-sm text-text-secondary">
          Contact:{" "}
          <a href="mailto:hello@qarar.app" className="text-accent-primary hover:underline">
            hello@qarar.app
          </a>
        </p>
        <Link href="/" className="mt-10 inline-block text-accent-primary hover:underline">
          ← Back home
        </Link>
      </article>
    </MarketingShell>
  );
}
