-- Durable fixed-window counters for AI endpoint rate limits.
-- Identifier values are SHA-256 hashes generated by the application.

create table if not exists public.ai_rate_limits (
  scope text not null,
  identifier_hash text not null,
  window_start timestamptz not null,
  count int not null default 0,
  updated_at timestamptz default now(),
  primary key (scope, identifier_hash, window_start)
);

alter table public.ai_rate_limits enable row level security;

create or replace function public.increment_ai_rate_limit(
  p_scope text,
  p_identifier_hash text,
  p_window_start timestamptz,
  p_limit int
)
returns table(allowed boolean, current_count int)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_count int;
begin
  insert into public.ai_rate_limits (scope, identifier_hash, window_start, count, updated_at)
  values (p_scope, p_identifier_hash, p_window_start, 1, now())
  on conflict (scope, identifier_hash, window_start)
  do update set
    count = public.ai_rate_limits.count + 1,
    updated_at = now()
  returning count into v_count;

  return query select v_count <= p_limit, v_count;
end;
$$;

revoke all on function public.increment_ai_rate_limit(text, text, timestamptz, int) from public;
